/** Auto-generated by scripts/cache-tool-favicons.mjs — do not edit by hand. */
export const TOOL_FAVICON_DIR = '/images/tool-favicons';

export const CACHED_TOOL_FAVICON_HOSTS = new Set<string>([
  "alphafold.ebi.ac.uk",
  "azimuth.hubmapconsortium.org",
  "bio-bigdata.hrbmu.edu.cn",
  "blast.ncbi.nlm.nih.gov",
  "cellprofiler.org",
  "cells.ucsc.edu",
  "cellxgene.cziscience.com",
  "chopchop.cbu.uib.no",
  "crispor.tefor.net",
  "crispresso.pinellolab.org",
  "cytoflow.github.io",
  "cytoflow.readthedocs.io",
  "evtrack.org",
  "flowrepository.org",
  "fragpipe.nesvilab.org",
  "genome.ucsc.edu",
  "giottosuite.readthedocs.io",
  "github.com",
  "imagej.net",
  "ko-fi.com",
  "microvesicles.org",
  "mirdb.org",
  "mirtarbase.cuhk.edu.cn",
  "mole.fit",
  "napari.org",
  "ngff.openmicroscopy.org",
  "panglaodb.se",
  "pga.mgh.harvard.edu",
  "primer3.ut.ee",
  "pubchem.ncbi.nlm.nih.gov",
  "qupath.github.io",
  "rnacentral.org",
  "rnasysu.com",
  "satijalab.org",
  "scanpy.readthedocs.io",
  "scvi-tools.org",
  "singlecell.broadinstitute.org",
  "skyline.ms",
  "squidpy.readthedocs.io",
  "stlearn.readthedocs.io",
  "tools.iedb.org",
  "www.addgene.org",
  "www.antibodypedia.com",
  "www.bioinformatics.org",
  "www.citeab.com",
  "www.ebi.ac.uk",
  "www.exocarta.org",
  "www.humancellatlas.org",
  "www.iedb.org",
  "www.immport.org",
  "www.isev.org",
  "www.itksnap.org",
  "www.maxquant.org",
  "www.ncbi.nlm.nih.gov",
  "www.openmicroscopy.org",
  "www.proteinatlas.org",
  "www.proteomexchange.org",
  "www.rcsb.org",
  "www.rgenome.net",
  "www.slicer.org",
  "www.targetscan.org",
  "www.uniprot.org",
]);

export function getCachedToolFaviconPath(hostname: string): string | null {
  if (!CACHED_TOOL_FAVICON_HOSTS.has(hostname)) return null;
  return `${TOOL_FAVICON_DIR}/${hostname}.png`;
}

/** Resolve a tool icon to a same-origin path. Never returns third-party favicon URLs. */
export function getToolFaviconSrc(href: string, iconUrl?: string | null): string | null {
  if (iconUrl && iconUrl.startsWith('/')) return iconUrl;

  if (!href.startsWith('http://') && !href.startsWith('https://')) return null;

  try {
    return getCachedToolFaviconPath(new URL(href).hostname);
  } catch {
    return null;
  }
}
