/**
 * Semantic storefront surfaces — prefer these over raw slate/gray utilities.
 * Night contrast for leftover slate/gray classes is handled by the
 * html.dark --color-slate/gray scale map in globals.css.
 */
export const uiSurfaces = {
  // Legacy flat keys. Keep these stable because they are used across the app.
  page: 'libereal-page',
  servicePage: 'libereal-service-page',
  panel: 'libereal-panel',
  panelStrong: 'libereal-panel-strong',
  toolbar: 'libereal-toolbar',
  pageDefault: 'libereal-page',
  pageService: 'libereal-service-page',
  panelDefault: 'libereal-panel',
  panelElevated: 'libereal-panel-strong',
  toolbarDefault: 'libereal-toolbar',
  button: 'libereal-button',
  buttonPrimary: 'libereal-button-primary',
  buttonSecondary: 'libereal-button-secondary text-[var(--brand-color-text-interactive)]',
  buttonGhost: 'libereal-button-ghost',
  buttonDanger: 'libereal-button-danger',
  chip: 'libereal-section-title text-sm font-semibold tracking-tight',
  activePill:
    'rounded-[var(--brand-border-radius)] bg-brand-700 px-3 py-1.5 text-sm font-semibold text-[var(--brand-color-primary-text)] shadow-[0_10px_24px_color-mix(in_srgb,var(--brand-color-primary)_22%,transparent)] transition hover:-translate-y-px hover:bg-brand-500 active:translate-y-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-color-focus-ring-readable)]',
  ghostPill: 'libereal-ghost-pill',
  disabledPill: 'libereal-disabled-pill',
  linkButton: 'libereal-link-button text-[var(--brand-color-text-interactive)]',
  primaryButton: 'libereal-primary-button',
  input: 'libereal-input placeholder:text-[var(--brand-color-text-placeholder-readable)]',
  inputDefault: 'libereal-input placeholder:text-[var(--brand-color-text-placeholder-readable)]',
  inputCompact: 'libereal-input libereal-input-compact placeholder:text-[var(--brand-color-text-placeholder-readable)]',
  inputError: 'libereal-input libereal-input-error placeholder:text-[var(--brand-color-text-placeholder-readable)]',
  modal: 'libereal-modal',
  modalBackdrop: 'libereal-modal-backdrop',
  badge: 'libereal-badge',
  badgeSuccess: 'libereal-badge libereal-badge-success',
  badgeWarning: 'libereal-badge libereal-badge-warning',
  badgeError: 'libereal-badge libereal-badge-error',
  badgeInfo: 'libereal-badge libereal-badge-info',
  skeleton: 'libereal-skeleton',
  status: 'libereal-status',
  statusSuccess: 'libereal-status libereal-status-success',
  statusWarning: 'libereal-status libereal-status-warning',
  statusError: 'libereal-status libereal-status-error',
  statusInfo: 'libereal-status libereal-status-info',
  mutedText: 'libereal-muted-text',
  titleText: 'libereal-title-text',
  text: 'text-[var(--brand-color-text)]',
  textSecondary: 'text-[var(--brand-color-text-secondary)]',
  textQuaternary: 'text-[var(--brand-color-text-quaternary)]',
  textInteractive: 'text-[var(--brand-color-text-interactive)]',
  textInteractiveHover: 'hover:text-[var(--brand-color-text-interactive-hover)]',
  textInteractiveActive: 'active:text-[var(--brand-color-text-interactive-active)]',
  border: 'border-[var(--brand-color-border)]',
  bgContainer: 'bg-[var(--brand-color-bg-container)]',
  bgLayout: 'bg-[var(--brand-color-bg-layout)]',
  focusRing:
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-color-focus-ring-readable)]',
  mobileNav: 'libereal-mobile-nav',
  mobileNavItem: 'libereal-mobile-nav-item',
  mobileNavItemActive: 'libereal-mobile-nav-item-active',
  mobilePopupControl: 'libereal-mobile-popup-control',
  mobilePopupDangerControl: 'libereal-mobile-popup-danger-control',
  /** Full-screen modal / sheet backdrop — above fixed site header, panel clears header */
  overlay:
    'fixed inset-0 z-site-overlay flex justify-center overflow-y-auto px-4 pb-4 pt-[calc(var(--site-header-height)+var(--site-header-gap))]',
  semantic: {
    page: {
      default: 'libereal-page',
      service: 'libereal-service-page',
    },
    panel: {
      default: 'libereal-panel',
      elevated: 'libereal-panel-strong',
    },
    toolbar: 'libereal-toolbar',
    button: {
      default: 'libereal-button',
      primary: 'libereal-button-primary',
      secondary: 'libereal-button-secondary text-[var(--brand-color-text-interactive)]',
      ghost: 'libereal-button-ghost',
      danger: 'libereal-button-danger',
    },
    input: {
      default: 'libereal-input placeholder:text-[var(--brand-color-text-placeholder-readable)]',
      compact: 'libereal-input libereal-input-compact placeholder:text-[var(--brand-color-text-placeholder-readable)]',
      error: 'libereal-input libereal-input-error placeholder:text-[var(--brand-color-text-placeholder-readable)]',
    },
    modal: {
      surface: 'libereal-modal',
      backdrop: 'libereal-modal-backdrop',
    },
    badge: {
      default: 'libereal-badge',
      success: 'libereal-badge libereal-badge-success',
      warning: 'libereal-badge libereal-badge-warning',
      error: 'libereal-badge libereal-badge-error',
      info: 'libereal-badge libereal-badge-info',
    },
    skeleton: 'libereal-skeleton',
    status: {
      default: 'libereal-status',
      success: 'libereal-status libereal-status-success',
      warning: 'libereal-status libereal-status-warning',
      error: 'libereal-status libereal-status-error',
      info: 'libereal-status libereal-status-info',
    },
  },
} as const;
